site_name: Dog Breed Collection
theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - table-reader
